using System.Text.Json.Nodes;
using Ariva.Core.Messaging;
using Ariva.Simulation.Api.Emulators.Aman;
using FluentAssertions;

namespace Ariva.UnitTests.Messaging.AsyncApi;

/// <summary>
/// ARV-067: docs/architecture/asyncapi.yaml and the topic table of wiki/08-Integration-Guide.md are what the code says.
/// A new topic, a changed message type or a renamed consumer group fails here until the document is regenerated
/// (ARIVA_UPDATE_ASYNCAPI=1 dotnet test --filter AsyncApiTests); the CLI validator in CI checks the result is valid AsyncAPI 3.
/// </summary>
public sealed class AsyncApiTests
{
    private const string WikiStart = "<!-- asyncapi-topics:start (generated by AsyncApiTests, do not edit) -->";
    private const string WikiEnd = "<!-- asyncapi-topics:end -->";
    private static readonly bool Update = Environment.GetEnvironmentVariable("ARIVA_UPDATE_ASYNCAPI") == "1";

    private static string Repository()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "Ariva.slnx")))
            directory = directory.Parent;
        return directory?.FullName ?? throw new InvalidOperationException("Ariva.slnx not found above the test output.");
    }

    [Fact]
    public void Document_Should_MatchTheCode()
    {
        var file = Path.Combine(Repository(), "docs", "architecture", "asyncapi.yaml");
        var generated = AsyncApiDocument.ToYaml(AsyncApiDocument.Build());
        if (Update)
            File.WriteAllText(file, generated);

        File.ReadAllText(file).ReplaceLineEndings("\n").Should().Be(generated,
            "the document is generated from KafkaTopics, TopicCatalog and the message types; regenerate it with ARIVA_UPDATE_ASYNCAPI=1");
    }

    [Fact]
    public void WikiTable_Should_MatchTheCode()
    {
        var file = Path.Combine(Repository(), "wiki", "08-Integration-Guide.md");
        var text = File.ReadAllText(file).ReplaceLineEndings("\n");
        var start = text.IndexOf(WikiStart, StringComparison.Ordinal);
        var end = text.IndexOf(WikiEnd, StringComparison.Ordinal);
        start.Should().BeGreaterThan(0, "the integration guide holds the generated topic table between its markers");
        end.Should().BeGreaterThan(start);
        var expected = text[..(start + WikiStart.Length)] + "\n" + AsyncApiDocument.WikiTable() + text[end..];
        if (Update)
            File.WriteAllText(file, expected);

        text.Should().Be(expected, "the topic table is generated; regenerate it with ARIVA_UPDATE_ASYNCAPI=1");
    }

    [Fact]
    public void EveryTopic_Should_BeDescribed_WithItsPayload()
    {
        TopicDescriptions.All.Keys.Should().BeEquivalentTo(KafkaTopics.All, "one description per KafkaTopics constant");
        foreach (var (topic, type) in AsyncApiDocument.EventTypes)
        {
            KafkaTopics.IsKnown(topic).Should().BeTrue();
            TopicDescriptions.All[topic].Producer.Should().NotBeNull("{0} carries {1}, so something produces it", topic, type.Name);
            TopicDescriptions.All[topic].Payload.Should().BeNull("an Ariva topic's type comes from its [KafkaTopic] attribute");
        }

        foreach (var (topic, description) in TopicDescriptions.All.Where(d => d.Value.Producer is not null))
            AsyncApiDocument.PayloadOf(topic).Should().NotBeNull("{0} has a producer, so it has a payload type", topic);
        foreach (var (topic, description) in TopicDescriptions.All.Where(d => d.Value.Reserved))
            AsyncApiDocument.EventTypes.Should().NotContainKey(topic, "a reserved topic has no message type yet ({0})", description.Summary);
    }

    [Fact]
    public void ConsumerGroups_Should_BeTheOnesTheHostsRegister()
    {
        // Each purpose appears as a string literal where the host registers its consumer (Ariva.Di or Ariva.Infra).
        var sources = Directory.EnumerateFiles(Path.Combine(Repository(), "Platform", "Backplane"), "*.cs", SearchOption.AllDirectories)
            .Where(f => f.Contains("Ariva.Di", StringComparison.Ordinal) || f.Contains("Ariva.Infra", StringComparison.Ordinal))
            .Where(f => !f.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}", StringComparison.Ordinal))
            .Select(File.ReadAllText)
            .ToList();
        var services = new[] { "main", "ingest", "stream", "cronz", "integration" };
        foreach (var consumer in TopicDescriptions.All.Values.SelectMany(d => d.Consumers))
        {
            services.Should().Contain(consumer.Service);
            sources.Should().Contain(s => s.Contains($"\"{consumer.Purpose}\"", StringComparison.Ordinal), "the group {0} is registered in code", consumer.GroupId);
        }
    }

    [Fact]
    public void EveryReference_Should_Resolve_AndEveryOperation_Should_UseItsChannelsMessages()
    {
        // What the AsyncAPI parser checks beyond the JSON Schema, so it holds whichever validator CI runs.
        var document = AsyncApiDocument.Build();
        var references = new List<string>();
        Collect(document, references);
        references.Should().NotBeEmpty();
        foreach (var reference in references)
        {
            reference.Should().StartWith("#/");
            JsonNode target = document;
            foreach (var part in reference[2..].Split('/'))
                target = target?[part.Replace("~1", "/", StringComparison.Ordinal).Replace("~0", "~", StringComparison.Ordinal)];
            target.Should().NotBeNull("{0} resolves", reference);
        }

        foreach (var (name, operation) in (JsonObject)document["operations"]!)
        {
            var channel = operation!["channel"]!["$ref"]!.GetValue<string>();
            foreach (var message in (JsonArray)operation["messages"]!)
                message!["$ref"]!.GetValue<string>().Should().StartWith(channel + "/messages/", "operation {0} sends or receives its channel's messages", name);
        }
    }

    private static void Collect(JsonNode node, List<string> references)
    {
        switch (node)
        {
            case JsonObject map:
                foreach (var (key, value) in map)
                {
                    if (key == "$ref") references.Add(value!.GetValue<string>());
                    else if (value is not null) Collect(value, references);
                }

                break;
            case JsonArray list:
                foreach (var item in list.Where(i => i is not null))
                    Collect(item!, references);
                break;
        }
    }

    [Fact]
    public void Simulator_Should_PublishAmansFeedOnTheKafkaTopics()
    {
        var simulated = AmanContracts.All.Select(AmanContracts.Topic).ToList();
        simulated.Should().BeEquivalentTo(KafkaTopics.All.Where(t => t.StartsWith("aman.feed.", StringComparison.Ordinal)),
            "the simulator's AMAN publishes exactly the topics Ariva consumes");
    }

    [Fact]
    public void AmanSchemas_Should_CarryAggregatesOnly()
    {
        // ADR-0010: no officer, traveller or document identifier in any AMAN contract (as LayeringTests checks the types).
        string[] identifiers =
        [
            "officer", "badge", "staff", "employee", "user", "person", "traveller", "traveler", "passenger", "passport", "document",
            "visa", "name", "nationality", "birth", "gender", "sex", "email", "phone", "address", "biometric", "face", "finger", "photo"
        ];
        // Counts whose names contain one of those words without being an identifier; a new one is added here on review.
        string[] aggregates = ["documentsprocessed", "passengersbylane"];
        var schemas = (JsonObject)AsyncApiDocument.Build()["components"]!["schemas"]!;
        foreach (var topic in KafkaTopics.All.Where(t => t.StartsWith("aman.feed.", StringComparison.Ordinal)))
        {
            var name = AsyncApiDocument.PayloadOf(topic).Name;
            var schema = (JsonObject)schemas[name]!;
            schema["additionalProperties"]!.GetValue<bool>().Should().BeFalse("Ariva dead-letters an unknown member of {0}", name);
            var properties = PropertyNames(schema).ToList();
            properties.Should().NotBeEmpty();
            foreach (var property in properties.Where(p => !aggregates.Contains(p)))
                identifiers.Should().NotContain(i => property.Contains(i, StringComparison.Ordinal), "{0}.{1} is an aggregate field", name, property);
        }
    }

    // Every property name in a schema, nested objects and array items included.
    private static IEnumerable<string> PropertyNames(JsonNode node) => node switch
    {
        JsonObject map => map.SelectMany(p => (p.Key == "properties" && p.Value is JsonObject properties
                ? properties.Select(q => q.Key.ToLowerInvariant())
                : [])
            .Concat(p.Value is null ? [] : PropertyNames(p.Value))),
        JsonArray list => list.Where(n => n is not null).SelectMany(n => PropertyNames(n!)),
        _ => []
    };
}
