namespace Ariva.Core.Domain.Entities;

/// <summary>
/// The plan image of a level (ARV-018): a PNG, JPEG or sanitised SVG kept in file storage under a generated key, with
/// its scale (metres per pixel) and the pixel where the level's floor origin lies, so zones and sensors in metres can
/// be drawn on it. One live plan per level; a new upload replaces the previous one.
/// </summary>
public class FloorPlan : BaseSoftDeletableEntity<FloorPlan>, ISiteBound
{
    public const long MaxBytes = 20L * 1024 * 1024;

    protected FloorPlan()
    {
    }

    public FloorPlan(Level level, string storageKey, string contentType, long sizeBytes, string sha256, string originalFileName,
        int? widthPixels, int? heightPixels, double metresPerPixel, double originX, double originY)
    {
        ArgumentNullException.ThrowIfNull(level);
        ArgumentException.ThrowIfNullOrWhiteSpace(storageKey);
        ArgumentException.ThrowIfNullOrWhiteSpace(contentType);
        if (sizeBytes is <= 0 or > MaxBytes)
            throw new ArgumentOutOfRangeException(nameof(sizeBytes), sizeBytes, "A floor plan is at most 20 MB.");
        Level = level;
        SiteCode = level.SiteCode;
        StorageKey = storageKey;
        ContentType = contentType;
        SizeBytes = sizeBytes;
        Sha256 = sha256;
        OriginalFileName = originalFileName;
        WidthPixels = widthPixels;
        HeightPixels = heightPixels;
        Calibrate(metresPerPixel, originX, originY);
    }

    public virtual Level Level { get; protected set; }
    public virtual string SiteCode { get; protected set; }

    /// <summary>Generated by Ariva (never the uploaded file name), for example "0199...a1.png".</summary>
    public virtual string StorageKey { get; protected set; }

    public virtual string ContentType { get; protected set; }
    public virtual long SizeBytes { get; protected set; }

    /// <summary>SHA-256 (hex) of the stored bytes, after SVG sanitising.</summary>
    public virtual string Sha256 { get; protected set; }

    /// <summary>The uploaded name, for display only; never used as a path.</summary>
    public virtual string OriginalFileName { get; protected set; }

    public virtual int? WidthPixels { get; protected set; }
    public virtual int? HeightPixels { get; protected set; }
    public virtual double MetresPerPixel { get; protected set; }

    /// <summary>The pixel (from the image's top left) where the level's floor origin (0, 0) lies.</summary>
    public virtual double OriginX { get; protected set; }

    public virtual double OriginY { get; protected set; }

    /// <summary>Sets the scale and origin, for example after aligning the plan to two surveyed reference points.</summary>
    public virtual void Calibrate(double metresPerPixel, double originX, double originY)
    {
        if (!double.IsFinite(metresPerPixel) || metresPerPixel <= 0 || metresPerPixel > 10)
            throw new ArgumentOutOfRangeException(nameof(metresPerPixel), metresPerPixel, "The scale is more than 0 and at most 10 metres per pixel.");
        if (!double.IsFinite(originX) || !double.IsFinite(originY) || Math.Abs(originX) > 1_000_000 || Math.Abs(originY) > 1_000_000)
            throw new ArgumentOutOfRangeException(nameof(originX), "The origin is a pixel within one million of the image.");
        MetresPerPixel = metresPerPixel;
        OriginX = originX;
        OriginY = originY;
    }
}
