<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoFixture" />
        <PackageReference Include="Bogus" />
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Moq" />
        <PackageReference Include="Testcontainers.PostgreSql" />
        <PackageReference Include="Testcontainers.Redis" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\..\..\GlobalSuppressions.cs" Link="GlobalSuppressions.cs" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\Ariva.Api.Common\appsettings.base.json">
            <Link>appsettings.base.json</Link>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="..\Ariva.Api.Common\appsettings.base.vm-local.json">
            <Link>appsettings.base.vm-local.json</Link>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="..\Ariva.Api.Common\appsettings.base.k8s-dev.json">
            <Link>appsettings.base.k8s-dev.json</Link>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="..\Ariva.Api.Common\appsettings.base.k8s-demo.json">
            <Link>appsettings.base.k8s-demo.json</Link>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="..\Ariva.Api.Common\appsettings.base.k8s-prd.json">
            <Link>appsettings.base.k8s-prd.json</Link>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Ariva.Core\Ariva.Core.csproj" />
        <ProjectReference Include="..\Ariva.Infra\Ariva.Infra.csproj" />
        <ProjectReference Include="..\Ariva.Di\Ariva.Di.csproj" />
        <ProjectReference Include="..\Ariva.Api.Common\Ariva.Api.Common.csproj" />
        <ProjectReference Include="..\..\Business\Ariva.Business.Contracts\Ariva.Business.Contracts.csproj" />
    </ItemGroup>

</Project>
